apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: vivo-api
  description: Spring Application
spec:
  owner: dev-team-2
  domain: acme-internal-apps
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vivo-api
  description: Spring Boot
  tags:
    - microservice
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=vivo-api'
spec:
  type: service
  lifecycle: alpha
  owner: dev-team-2
  system: vivo-api
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgreSQL
  description: PostgreSQL Service
spec:
  type: database
  owner: platform-team
  system: vivo-api
---