apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: vivo-api
  namespace: vivo-4-0
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: vivo-api
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: ssh://git@github.com/dprocha/vivo-api.git
      ref:
        branch: main
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: postgres
  serviceClaims:
    - name: postgres
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: vivo-api-db-claim # name must match the service claim name